# Generated by Django 5.2.10 on 2026-02-18 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentik_crypto",
            "0007_rename_crypto_certref_cert_idx_authentik_c_certifi_7d9d4e_idx_and_more",
        ),
        ("authentik_sources_saml", "0022_saml_multi_idp"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="samlidp",
            new_name="authentik_s_source__b73723_idx",
            old_name="authentik_s_source_i_2d0c4b_idx",
        ),
        migrations.RenameIndex(
            model_name="samlidp",
            new_name="authentik_s_source__460b41_idx",
            old_name="authentik_s_source_e_2f0e90_idx",
        ),
        migrations.AlterField(
            model_name="samlidp",
            name="digest_algorithm",
            field=models.TextField(
                choices=[
                    ("http://www.w3.org/2000/09/xmldsig#sha1", "SHA1"),
                    ("http://www.w3.org/2001/04/xmlenc#sha256", "SHA256"),
                    ("http://www.w3.org/2001/04/xmldsig-more#sha384", "SHA384"),
                    ("http://www.w3.org/2001/04/xmlenc#sha512", "SHA512"),
                ],
                default="http://www.w3.org/2001/04/xmlenc#sha256",
            ),
        ),
        migrations.AlterField(
            model_name="samlidp",
            name="encryption_kp",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="When selected, incoming assertions are encrypted by the IdP using the public key of the encryption keypair. The assertion is decrypted by the SP using the the private key.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="authentik_crypto.certificatekeypair",
                verbose_name="Encryption Keypair",
            ),
        ),
        migrations.AlterField(
            model_name="samlidp",
            name="metadata_hash",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="sha256 hex digest of normalized metadata snapshot.",
                max_length=64,
                null=True,
                verbose_name="Metadata hash",
            ),
        ),
        migrations.AlterField(
            model_name="samlidp",
            name="metadata_last_import",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Timestamp of the last successful metadata import.",
                null=True,
                verbose_name="Metadata last import",
            ),
        ),
        migrations.AlterField(
            model_name="samlidp",
            name="metadata_snapshot",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Canonical snapshot built from SAML metadata (JSON).",
                null=True,
                verbose_name="Metadata snapshot",
            ),
        ),
        migrations.AlterField(
            model_name="samlidp",
            name="name_id_policy",
            field=models.TextField(
                choices=[
                    ("urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress", "Email"),
                    ("urn:oasis:names:tc:SAML:2.0:nameid-format:persistent", "Persistent"),
                    ("urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName", "X509"),
                    (
                        "urn:oasis:names:tc:SAML:2.0:nameid-format:WindowsDomainQualifiedName",
                        "Windows",
                    ),
                    ("urn:oasis:names:tc:SAML:2.0:nameid-format:transient", "Transient"),
                    ("urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified", "Unspecified"),
                ],
                default="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent",
                help_text="NameID Policy sent to the IdP. Can be unset, in which case no Policy is sent.",
            ),
        ),
        migrations.AlterField(
            model_name="samlidp",
            name="signature_algorithm",
            field=models.TextField(
                choices=[
                    ("http://www.w3.org/2000/09/xmldsig#rsa-sha1", "RSA-SHA1"),
                    ("http://www.w3.org/2001/04/xmldsig-more#rsa-sha256", "RSA-SHA256"),
                    ("http://www.w3.org/2001/04/xmldsig-more#rsa-sha384", "RSA-SHA384"),
                    ("http://www.w3.org/2001/04/xmldsig-more#rsa-sha512", "RSA-SHA512"),
                    ("http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha1", "ECDSA-SHA1"),
                    ("http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256", "ECDSA-SHA256"),
                    ("http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384", "ECDSA-SHA384"),
                    ("http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512", "ECDSA-SHA512"),
                    ("http://www.w3.org/2000/09/xmldsig#dsa-sha1", "DSA-SHA1"),
                ],
                default="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
            ),
        ),
    ]
