# Generated by Django 5.2.10 on 2026-02-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentik_sources_saml",
            "0023_rename_authentik_s_source_i_2d0c4b_idx_authentik_s_source__b73723_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="samlidp",
            name="encryption_kp_mode",
            field=models.CharField(
                choices=[
                    ("inherit", "Inherit source setting"),
                    ("set", "Use local key"),
                    ("none", "Disable key (no key)"),
                ],
                default="inherit",
                help_text="How encryption_kp is resolved: inherit source, use local key, or explicitly disable encryption key.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="samlidp",
            name="freeze_encryption_kp",
            field=models.BooleanField(
                default=False,
                help_text="Do not overwrite encryption_kp during metadata apply/import. Useful for certificate rollover handling or local pinning.",
            ),
        ),
        migrations.AddField(
            model_name="samlidp",
            name="freeze_signing_kp",
            field=models.BooleanField(
                default=False,
                help_text="Do not overwrite signing_kp during metadata apply/import. Useful for certificate rollover handling or local pinning.",
            ),
        ),
        migrations.AddField(
            model_name="samlidp",
            name="freeze_verification_kp",
            field=models.BooleanField(
                default=False,
                help_text="Do not overwrite verification_kp during metadata apply/import. Useful for certificate rollover handling or local pinning.",
            ),
        ),
        migrations.AddField(
            model_name="samlidp",
            name="has_local_override",
            field=models.BooleanField(
                default=False,
                help_text="UI/diagnostic flag indicating local changes may exist relative to metadata-derived defaults. Protocol processing does not read this flag.",
            ),
        ),
        migrations.AddField(
            model_name="samlidp",
            name="signing_kp_mode",
            field=models.CharField(
                choices=[
                    ("inherit", "Inherit source setting"),
                    ("set", "Use local key"),
                    ("none", "Disable key (no key)"),
                ],
                default="inherit",
                help_text="How signing_kp is resolved: inherit source, use local key, or explicitly disable signing key.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="samlidp",
            name="verification_kp_mode",
            field=models.CharField(
                choices=[
                    ("inherit", "Inherit source setting"),
                    ("set", "Use local key"),
                    ("none", "Disable key (no key)"),
                ],
                default="inherit",
                help_text="How verification_kp is resolved: inherit source, use local key, or explicitly disable verification key.",
                max_length=16,
            ),
        ),
    ]
