# Generated by Django 5.2.10 on 2026-02-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_sources_saml", "0024_samlidp_encryption_kp_mode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="samlidp",
            name="encryption_kp_mode",
        ),
        migrations.RemoveField(
            model_name="samlidp",
            name="signing_kp_mode",
        ),
        migrations.RemoveField(
            model_name="samlidp",
            name="verification_kp_mode",
        ),
        migrations.AddField(
            model_name="samlidp",
            name="encryption_kp_override",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, use this IdP's local encryption_kp (may be null to disable). If disabled, inherit source setting.",
            ),
        ),
        migrations.AddField(
            model_name="samlidp",
            name="signing_kp_override",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, use this IdP's local signing_kp (may be null to disable). If disabled, inherit source setting.",
            ),
        ),
        migrations.AddField(
            model_name="samlidp",
            name="verification_kp_override",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, use this IdP's local verification_kp (may be null to disable). If disabled, inherit source setting.",
            ),
        ),
    ]
