# Generated by Django 5.2.10 on 2026-02-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_providers_saml", "0023_remove_samlsp_encryption_kp_mode_and_more"),
        ("authentik_sources_saml", "0025_remove_samlidp_encryption_kp_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="samlidp",
            name="property_mappings",
            field=models.ManyToManyField(
                blank=True,
                help_text="Per-IdP property mappings. If empty, provider property mappings are used.",
                related_name="samlidp_overrides",
                to="authentik_providers_saml.samlpropertymapping",
            ),
        ),
        migrations.AddField(
            model_name="samlidp",
            name="property_mappings_override",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, use this SAMLIDP's property mappings instead of provider mappings. An empty set is treated as an explicit override (no attributes).",
            ),
        ),
    ]
