# Generated by Django 5.2.10 on 2026-02-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_sources_saml", "0026_samlidp_property_mappings_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="samlidp",
            name="property_mappings",
        ),
        migrations.RemoveField(
            model_name="samlidp",
            name="property_mappings_override",
        ),
    ]
