/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BindingTypeEnum } from "./BindingTypeEnum";
import { BindingTypeEnumFromJSON, BindingTypeEnumToJSON } from "./BindingTypeEnum";
import type { DigestAlgorithmEnum } from "./DigestAlgorithmEnum";
import { DigestAlgorithmEnumFromJSON, DigestAlgorithmEnumToJSON } from "./DigestAlgorithmEnum";
import type { SAMLNameIDPolicyEnum } from "./SAMLNameIDPolicyEnum";
import { SAMLNameIDPolicyEnumFromJSON, SAMLNameIDPolicyEnumToJSON } from "./SAMLNameIDPolicyEnum";
import type { SignatureAlgorithmEnum } from "./SignatureAlgorithmEnum";
import {
    SignatureAlgorithmEnumFromJSON,
    SignatureAlgorithmEnumToJSON,
} from "./SignatureAlgorithmEnum";

/**
 * Serializer for nested SAML identity provider entities.
 * @export
 * @interface PatchedSAMLIDPRequest
 */
export interface PatchedSAMLIDPRequest {
    /**
     *
     */
    name?: string;
    /**
     * SAML EntityID (Issuer)
     */
    entityId?: string;
    /**
     *
     */
    enabled?: boolean;
    /**
     * URL that the initial Login request is sent to.
     */
    ssoUrl?: string;
    /**
     * Optional URL if your IDP supports Single-Logout.
     */
    sloUrl?: string | null;
    /**
     *
     */
    allowIdpInitiated?: boolean;
    /**
     *
     */
    nameIdPolicy?: SAMLNameIDPolicyEnum;
    /**
     *
     */
    bindingType?: BindingTypeEnum;
    /**
     *
     */
    digestAlgorithm?: DigestAlgorithmEnum;
    /**
     *
     */
    signatureAlgorithm?: SignatureAlgorithmEnum;
    /**
     *
     */
    signedAssertion?: boolean;
    /**
     *
     */
    signedResponse?: boolean;
    /**
     *
     */
    verificationKp?: string | null;
    /**
     *
     */
    signingKp?: string | null;
    /**
     *
     */
    encryptionKp?: string | null;
    /**
     *
     */
    verificationKpRing?: string | null;
    /**
     *
     */
    signingKpRing?: string | null;
    /**
     *
     */
    encryptionKpRing?: string | null;
    /**
     * Use local key; otherwise inherit from owner.
     */
    verificationKpOverride?: boolean;
    /**
     * Use local key; otherwise inherit from owner.
     */
    signingKpOverride?: boolean;
    /**
     * Use local key; otherwise inherit from owner.
     */
    encryptionKpOverride?: boolean;
    /**
     *
     */
    freezeVerificationKp?: boolean;
    /**
     *
     */
    freezeSigningKp?: boolean;
    /**
     *
     */
    freezeEncryptionKp?: boolean;
    /**
     *
     */
    localOverrideSet?: boolean;
}

/**
 * Check if a given object implements the PatchedSAMLIDPRequest interface.
 */
export function instanceOfPatchedSAMLIDPRequest(value: object): value is PatchedSAMLIDPRequest {
    return true;
}

export function PatchedSAMLIDPRequestFromJSON(json: any): PatchedSAMLIDPRequest {
    return PatchedSAMLIDPRequestFromJSONTyped(json, false);
}

export function PatchedSAMLIDPRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PatchedSAMLIDPRequest {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"] == null ? undefined : json["name"],
        entityId: json["entity_id"] == null ? undefined : json["entity_id"],
        enabled: json["enabled"] == null ? undefined : json["enabled"],
        ssoUrl: json["sso_url"] == null ? undefined : json["sso_url"],
        sloUrl:
            json["slo_url"] === undefined
                ? undefined
                : json["slo_url"] === null
                  ? null
                  : json["slo_url"],
        allowIdpInitiated:
            json["allow_idp_initiated"] == null ? undefined : json["allow_idp_initiated"],
        nameIdPolicy:
            json["name_id_policy"] == null
                ? undefined
                : SAMLNameIDPolicyEnumFromJSON(json["name_id_policy"]),
        bindingType:
            json["binding_type"] == null
                ? undefined
                : BindingTypeEnumFromJSON(json["binding_type"]),
        digestAlgorithm:
            json["digest_algorithm"] == null
                ? undefined
                : DigestAlgorithmEnumFromJSON(json["digest_algorithm"]),
        signatureAlgorithm:
            json["signature_algorithm"] == null
                ? undefined
                : SignatureAlgorithmEnumFromJSON(json["signature_algorithm"]),
        signedAssertion: json["signed_assertion"] == null ? undefined : json["signed_assertion"],
        signedResponse: json["signed_response"] == null ? undefined : json["signed_response"],
        verificationKp:
            json["verification_kp"] === undefined
                ? undefined
                : json["verification_kp"] === null
                  ? null
                  : json["verification_kp"],
        signingKp:
            json["signing_kp"] === undefined
                ? undefined
                : json["signing_kp"] === null
                  ? null
                  : json["signing_kp"],
        encryptionKp:
            json["encryption_kp"] === undefined
                ? undefined
                : json["encryption_kp"] === null
                  ? null
                  : json["encryption_kp"],
        verificationKpRing:
            json["verification_kp_ring"] === undefined
                ? undefined
                : json["verification_kp_ring"] === null
                  ? null
                  : json["verification_kp_ring"],
        signingKpRing:
            json["signing_kp_ring"] === undefined
                ? undefined
                : json["signing_kp_ring"] === null
                  ? null
                  : json["signing_kp_ring"],
        encryptionKpRing:
            json["encryption_kp_ring"] === undefined
                ? undefined
                : json["encryption_kp_ring"] === null
                  ? null
                  : json["encryption_kp_ring"],
        verificationKpOverride:
            json["verification_kp_override"] == null ? undefined : json["verification_kp_override"],
        signingKpOverride:
            json["signing_kp_override"] == null ? undefined : json["signing_kp_override"],
        encryptionKpOverride:
            json["encryption_kp_override"] == null ? undefined : json["encryption_kp_override"],
        freezeVerificationKp:
            json["freeze_verification_kp"] == null ? undefined : json["freeze_verification_kp"],
        freezeSigningKp: json["freeze_signing_kp"] == null ? undefined : json["freeze_signing_kp"],
        freezeEncryptionKp:
            json["freeze_encryption_kp"] == null ? undefined : json["freeze_encryption_kp"],
        localOverrideSet:
            json["local_override_set"] == null ? undefined : json["local_override_set"],
    };
}

export function PatchedSAMLIDPRequestToJSON(json: any): PatchedSAMLIDPRequest {
    return PatchedSAMLIDPRequestToJSONTyped(json, false);
}

export function PatchedSAMLIDPRequestToJSONTyped(
    value?: PatchedSAMLIDPRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        entity_id: value["entityId"],
        enabled: value["enabled"],
        sso_url: value["ssoUrl"],
        slo_url: value["sloUrl"],
        allow_idp_initiated: value["allowIdpInitiated"],
        name_id_policy: SAMLNameIDPolicyEnumToJSON(value["nameIdPolicy"]),
        binding_type: BindingTypeEnumToJSON(value["bindingType"]),
        digest_algorithm: DigestAlgorithmEnumToJSON(value["digestAlgorithm"]),
        signature_algorithm: SignatureAlgorithmEnumToJSON(value["signatureAlgorithm"]),
        signed_assertion: value["signedAssertion"],
        signed_response: value["signedResponse"],
        verification_kp: value["verificationKp"],
        signing_kp: value["signingKp"],
        encryption_kp: value["encryptionKp"],
        verification_kp_ring: value["verificationKpRing"],
        signing_kp_ring: value["signingKpRing"],
        encryption_kp_ring: value["encryptionKpRing"],
        verification_kp_override: value["verificationKpOverride"],
        signing_kp_override: value["signingKpOverride"],
        encryption_kp_override: value["encryptionKpOverride"],
        freeze_verification_kp: value["freezeVerificationKp"],
        freeze_signing_kp: value["freezeSigningKp"],
        freeze_encryption_kp: value["freezeEncryptionKp"],
        local_override_set: value["localOverrideSet"],
    };
}
