/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SAMLBindingsEnum } from "./SAMLBindingsEnum";
import { SAMLBindingsEnumFromJSON, SAMLBindingsEnumToJSON } from "./SAMLBindingsEnum";
import type { SAMLNameIDPolicyEnum } from "./SAMLNameIDPolicyEnum";
import { SAMLNameIDPolicyEnumFromJSON, SAMLNameIDPolicyEnumToJSON } from "./SAMLNameIDPolicyEnum";

/**
 * Serializer for nested SAML service provider entities.
 * @export
 * @interface PatchedSAMLSPRequest
 */
export interface PatchedSAMLSPRequest {
    /**
     *
     */
    name?: string;
    /**
     * SAML EntityID (Issuer)
     */
    entityId?: string;
    /**
     *
     */
    enabled?: boolean;
    /**
     *
     */
    acsUrl?: string;
    /**
     *
     */
    spBinding?: SAMLBindingsEnum;
    /**
     *
     */
    slsUrl?: string;
    /**
     *
     */
    slsBinding?: SAMLBindingsEnum;
    /**
     *
     */
    authnRequestsSigned?: boolean;
    /**
     *
     */
    wantAssertionsSigned?: boolean;
    /**
     *
     */
    nameIdPolicy?: SAMLNameIDPolicyEnum;
    /**
     *
     */
    verificationKp?: string | null;
    /**
     *
     */
    signingKp?: string | null;
    /**
     *
     */
    encryptionKp?: string | null;
    /**
     *
     */
    verificationKpRing?: string | null;
    /**
     *
     */
    signingKpRing?: string | null;
    /**
     *
     */
    encryptionKpRing?: string | null;
    /**
     * Use local key; otherwise inherit from owner.
     */
    verificationKpOverride?: boolean;
    /**
     * Use local key; otherwise inherit from owner.
     */
    signingKpOverride?: boolean;
    /**
     * Use local key; otherwise inherit from owner.
     */
    encryptionKpOverride?: boolean;
    /**
     *
     */
    freezeVerificationKp?: boolean;
    /**
     *
     */
    freezeSigningKp?: boolean;
    /**
     *
     */
    freezeEncryptionKp?: boolean;
    /**
     *
     */
    localOverrideSet?: boolean;
    /**
     * If enabled, use this SAMLSP's property mappings instead of provider mappings.
     */
    propertyMappingsOverride?: boolean;
    /**
     * Per-SP property mappings.
     */
    propertyMappings?: Array<string>;
}

/**
 * Check if a given object implements the PatchedSAMLSPRequest interface.
 */
export function instanceOfPatchedSAMLSPRequest(value: object): value is PatchedSAMLSPRequest {
    return true;
}

export function PatchedSAMLSPRequestFromJSON(json: any): PatchedSAMLSPRequest {
    return PatchedSAMLSPRequestFromJSONTyped(json, false);
}

export function PatchedSAMLSPRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PatchedSAMLSPRequest {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"] == null ? undefined : json["name"],
        entityId: json["entity_id"] == null ? undefined : json["entity_id"],
        enabled: json["enabled"] == null ? undefined : json["enabled"],
        acsUrl: json["acs_url"] == null ? undefined : json["acs_url"],
        spBinding:
            json["sp_binding"] == null ? undefined : SAMLBindingsEnumFromJSON(json["sp_binding"]),
        slsUrl: json["sls_url"] == null ? undefined : json["sls_url"],
        slsBinding:
            json["sls_binding"] == null ? undefined : SAMLBindingsEnumFromJSON(json["sls_binding"]),
        authnRequestsSigned:
            json["authn_requests_signed"] == null ? undefined : json["authn_requests_signed"],
        wantAssertionsSigned:
            json["want_assertions_signed"] == null ? undefined : json["want_assertions_signed"],
        nameIdPolicy:
            json["name_id_policy"] == null
                ? undefined
                : SAMLNameIDPolicyEnumFromJSON(json["name_id_policy"]),
        verificationKp:
            json["verification_kp"] === undefined
                ? undefined
                : json["verification_kp"] === null
                  ? null
                  : json["verification_kp"],
        signingKp:
            json["signing_kp"] === undefined
                ? undefined
                : json["signing_kp"] === null
                  ? null
                  : json["signing_kp"],
        encryptionKp:
            json["encryption_kp"] === undefined
                ? undefined
                : json["encryption_kp"] === null
                  ? null
                  : json["encryption_kp"],
        verificationKpRing:
            json["verification_kp_ring"] === undefined
                ? undefined
                : json["verification_kp_ring"] === null
                  ? null
                  : json["verification_kp_ring"],
        signingKpRing:
            json["signing_kp_ring"] === undefined
                ? undefined
                : json["signing_kp_ring"] === null
                  ? null
                  : json["signing_kp_ring"],
        encryptionKpRing:
            json["encryption_kp_ring"] === undefined
                ? undefined
                : json["encryption_kp_ring"] === null
                  ? null
                  : json["encryption_kp_ring"],
        verificationKpOverride:
            json["verification_kp_override"] == null ? undefined : json["verification_kp_override"],
        signingKpOverride:
            json["signing_kp_override"] == null ? undefined : json["signing_kp_override"],
        encryptionKpOverride:
            json["encryption_kp_override"] == null ? undefined : json["encryption_kp_override"],
        freezeVerificationKp:
            json["freeze_verification_kp"] == null ? undefined : json["freeze_verification_kp"],
        freezeSigningKp: json["freeze_signing_kp"] == null ? undefined : json["freeze_signing_kp"],
        freezeEncryptionKp:
            json["freeze_encryption_kp"] == null ? undefined : json["freeze_encryption_kp"],
        localOverrideSet:
            json["local_override_set"] == null ? undefined : json["local_override_set"],
        propertyMappingsOverride:
            json["property_mappings_override"] == null
                ? undefined
                : json["property_mappings_override"],
        propertyMappings: json["property_mappings"] == null ? undefined : json["property_mappings"],
    };
}

export function PatchedSAMLSPRequestToJSON(json: any): PatchedSAMLSPRequest {
    return PatchedSAMLSPRequestToJSONTyped(json, false);
}

export function PatchedSAMLSPRequestToJSONTyped(
    value?: PatchedSAMLSPRequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        entity_id: value["entityId"],
        enabled: value["enabled"],
        acs_url: value["acsUrl"],
        sp_binding: SAMLBindingsEnumToJSON(value["spBinding"]),
        sls_url: value["slsUrl"],
        sls_binding: SAMLBindingsEnumToJSON(value["slsBinding"]),
        authn_requests_signed: value["authnRequestsSigned"],
        want_assertions_signed: value["wantAssertionsSigned"],
        name_id_policy: SAMLNameIDPolicyEnumToJSON(value["nameIdPolicy"]),
        verification_kp: value["verificationKp"],
        signing_kp: value["signingKp"],
        encryption_kp: value["encryptionKp"],
        verification_kp_ring: value["verificationKpRing"],
        signing_kp_ring: value["signingKpRing"],
        encryption_kp_ring: value["encryptionKpRing"],
        verification_kp_override: value["verificationKpOverride"],
        signing_kp_override: value["signingKpOverride"],
        encryption_kp_override: value["encryptionKpOverride"],
        freeze_verification_kp: value["freezeVerificationKp"],
        freeze_signing_kp: value["freezeSigningKp"],
        freeze_encryption_kp: value["freezeEncryptionKp"],
        local_override_set: value["localOverrideSet"],
        property_mappings_override: value["propertyMappingsOverride"],
        property_mappings: value["propertyMappings"],
    };
}
