/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AcsBindingEnum } from "./AcsBindingEnum";
import { AcsBindingEnumFromJSON, AcsBindingEnumToJSON } from "./AcsBindingEnum";
import type { NameIdPolicyF88Enum } from "./NameIdPolicyF88Enum";
import { NameIdPolicyF88EnumFromJSON, NameIdPolicyF88EnumToJSON } from "./NameIdPolicyF88Enum";
import type { SlsBinding557Enum } from "./SlsBinding557Enum";
import { SlsBinding557EnumFromJSON, SlsBinding557EnumToJSON } from "./SlsBinding557Enum";

/**
 * Serializer for SP DTO payloads used by preview/apply.
 * @export
 * @interface SAMLSPDTORequest
 */
export interface SAMLSPDTORequest {
    /**
     *
     */
    entityId: string;
    /**
     *
     */
    displayName?: string | null;
    /**
     *
     */
    acsBinding: AcsBindingEnum;
    /**
     *
     */
    acsLocation: string;
    /**
     *
     */
    authNRequestSigned?: boolean;
    /**
     *
     */
    assertionSigned?: boolean;
    /**
     *
     */
    nameIdPolicy?: NameIdPolicyF88Enum;
    /**
     *
     */
    slsBinding?: SlsBinding557Enum | null;
    /**
     *
     */
    slsLocation?: string | null;
    /**
     *
     */
    signingCertPems?: Array<string>;
    /**
     *
     */
    encryptionCertPems?: Array<string>;
}

/**
 * Check if a given object implements the SAMLSPDTORequest interface.
 */
export function instanceOfSAMLSPDTORequest(value: object): value is SAMLSPDTORequest {
    if (
        (!("entityId" in (value as Record<string, any>)) &&
            !("entity_id" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["entityId"] === undefined &&
            (value as Record<string, any>)["entity_id"] === undefined)
    )
        return false;
    if (
        (!("acsBinding" in (value as Record<string, any>)) &&
            !("acs_binding" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["acsBinding"] === undefined &&
            (value as Record<string, any>)["acs_binding"] === undefined)
    )
        return false;
    if (
        (!("acsLocation" in (value as Record<string, any>)) &&
            !("acs_location" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["acsLocation"] === undefined &&
            (value as Record<string, any>)["acs_location"] === undefined)
    )
        return false;
    return true;
}

export function SAMLSPDTORequestFromJSON(json: any): SAMLSPDTORequest {
    return SAMLSPDTORequestFromJSONTyped(json, false);
}

export function SAMLSPDTORequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): SAMLSPDTORequest {
    if (json == null) {
        return json;
    }
    return {
        entityId: json["entity_id"],
        displayName:
            json["display_name"] === undefined
                ? undefined
                : json["display_name"] === null
                  ? null
                  : json["display_name"],
        acsBinding: AcsBindingEnumFromJSON(json["acs_binding"]),
        acsLocation: json["acs_location"],
        authNRequestSigned:
            json["auth_n_request_signed"] == null ? undefined : json["auth_n_request_signed"],
        assertionSigned: json["assertion_signed"] == null ? undefined : json["assertion_signed"],
        nameIdPolicy:
            json["name_id_policy"] == null
                ? undefined
                : NameIdPolicyF88EnumFromJSON(json["name_id_policy"]),
        slsBinding:
            json["sls_binding"] === undefined
                ? undefined
                : json["sls_binding"] === null
                  ? null
                  : SlsBinding557EnumFromJSON(json["sls_binding"]),
        slsLocation:
            json["sls_location"] === undefined
                ? undefined
                : json["sls_location"] === null
                  ? null
                  : json["sls_location"],
        signingCertPems: json["signing_cert_pems"] == null ? undefined : json["signing_cert_pems"],
        encryptionCertPems:
            json["encryption_cert_pems"] == null ? undefined : json["encryption_cert_pems"],
    };
}

export function SAMLSPDTORequestToJSON(json: any): SAMLSPDTORequest {
    return SAMLSPDTORequestToJSONTyped(json, false);
}

export function SAMLSPDTORequestToJSONTyped(
    value?: SAMLSPDTORequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        entity_id: value["entityId"],
        display_name: value["displayName"],
        acs_binding: AcsBindingEnumToJSON(value["acsBinding"]),
        acs_location: value["acsLocation"],
        auth_n_request_signed: value["authNRequestSigned"],
        assertion_signed: value["assertionSigned"],
        name_id_policy: NameIdPolicyF88EnumToJSON(value["nameIdPolicy"]),
        sls_binding: SlsBinding557EnumToJSON(value["slsBinding"]),
        sls_location: value["slsLocation"],
        signing_cert_pems: value["signingCertPems"],
        encryption_cert_pems: value["encryptionCertPems"],
    };
}
