/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { parseDateTime } from "../runtime";
import type { BindingTypeEnum } from "./BindingTypeEnum";
import { BindingTypeEnumFromJSON, BindingTypeEnumToJSON } from "./BindingTypeEnum";
import type { DigestAlgorithmEnum } from "./DigestAlgorithmEnum";
import { DigestAlgorithmEnumFromJSON, DigestAlgorithmEnumToJSON } from "./DigestAlgorithmEnum";
import type { SAMLNameIDPolicyEnum } from "./SAMLNameIDPolicyEnum";
import { SAMLNameIDPolicyEnumFromJSON, SAMLNameIDPolicyEnumToJSON } from "./SAMLNameIDPolicyEnum";
import type { SignatureAlgorithmEnum } from "./SignatureAlgorithmEnum";
import {
    SignatureAlgorithmEnumFromJSON,
    SignatureAlgorithmEnumToJSON,
} from "./SignatureAlgorithmEnum";

/**
 * Serializer for nested SAML identity provider entities.
 * @export
 * @interface SAMLIDP
 */
export interface SAMLIDP {
    /**
     *
     */
    readonly pk: number;
    /**
     *
     */
    readonly uuid: string;
    /**
     *
     */
    name?: string;
    /**
     * SAML EntityID (Issuer)
     */
    entityId: string;
    /**
     *
     */
    enabled?: boolean;
    /**
     * URL that the initial Login request is sent to.
     */
    ssoUrl: string;
    /**
     * Optional URL if your IDP supports Single-Logout.
     */
    sloUrl?: string | null;
    /**
     *
     */
    allowIdpInitiated?: boolean;
    /**
     *
     */
    nameIdPolicy?: SAMLNameIDPolicyEnum;
    /**
     *
     */
    bindingType?: BindingTypeEnum;
    /**
     *
     */
    digestAlgorithm?: DigestAlgorithmEnum;
    /**
     *
     */
    signatureAlgorithm?: SignatureAlgorithmEnum;
    /**
     *
     */
    signedAssertion?: boolean;
    /**
     *
     */
    signedResponse?: boolean;
    /**
     *
     */
    verificationKp?: string | null;
    /**
     *
     */
    signingKp?: string | null;
    /**
     *
     */
    encryptionKp?: string | null;
    /**
     *
     */
    verificationKpRing?: string | null;
    /**
     *
     */
    signingKpRing?: string | null;
    /**
     *
     */
    encryptionKpRing?: string | null;
    /**
     * Use local key; otherwise inherit from owner.
     */
    verificationKpOverride?: boolean;
    /**
     * Use local key; otherwise inherit from owner.
     */
    signingKpOverride?: boolean;
    /**
     * Use local key; otherwise inherit from owner.
     */
    encryptionKpOverride?: boolean;
    /**
     *
     */
    freezeVerificationKp?: boolean;
    /**
     *
     */
    freezeSigningKp?: boolean;
    /**
     *
     */
    freezeEncryptionKp?: boolean;
    /**
     *
     */
    localOverrideSet?: boolean;
    /**
     *
     */
    readonly metadataSnapshot: { [key: string]: any };
    /**
     *
     */
    readonly metadataLastImport: Date | null;
    /**
     *
     */
    readonly metadataHash: string;
    /**
     *
     */
    readonly created: Date;
    /**
     *
     */
    readonly lastUpdated: Date;
}

/**
 * Check if a given object implements the SAMLIDP interface.
 */
export function instanceOfSAMLIDP(value: object): value is SAMLIDP {
    if (!("pk" in value) || value["pk"] === undefined) return false;
    if (!("uuid" in value) || value["uuid"] === undefined) return false;
    if (
        (!("entityId" in (value as Record<string, any>)) &&
            !("entity_id" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["entityId"] === undefined &&
            (value as Record<string, any>)["entity_id"] === undefined)
    )
        return false;
    if (
        (!("ssoUrl" in (value as Record<string, any>)) &&
            !("sso_url" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["ssoUrl"] === undefined &&
            (value as Record<string, any>)["sso_url"] === undefined)
    )
        return false;
    if (
        (!("metadataSnapshot" in (value as Record<string, any>)) &&
            !("metadata_snapshot" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["metadataSnapshot"] === undefined &&
            (value as Record<string, any>)["metadata_snapshot"] === undefined)
    )
        return false;
    if (
        (!("metadataLastImport" in (value as Record<string, any>)) &&
            !("metadata_last_import" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["metadataLastImport"] === undefined &&
            (value as Record<string, any>)["metadata_last_import"] === undefined)
    )
        return false;
    if (
        (!("metadataHash" in (value as Record<string, any>)) &&
            !("metadata_hash" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["metadataHash"] === undefined &&
            (value as Record<string, any>)["metadata_hash"] === undefined)
    )
        return false;
    if (!("created" in value) || value["created"] === undefined) return false;
    if (
        (!("lastUpdated" in (value as Record<string, any>)) &&
            !("last_updated" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["lastUpdated"] === undefined &&
            (value as Record<string, any>)["last_updated"] === undefined)
    )
        return false;
    return true;
}

export function SAMLIDPFromJSON(json: any): SAMLIDP {
    return SAMLIDPFromJSONTyped(json, false);
}

export function SAMLIDPFromJSONTyped(json: any, ignoreDiscriminator: boolean): SAMLIDP {
    if (json == null) {
        return json;
    }
    return {
        pk: json["pk"],
        uuid: json["uuid"],
        name: json["name"] == null ? undefined : json["name"],
        entityId: json["entity_id"],
        enabled: json["enabled"] == null ? undefined : json["enabled"],
        ssoUrl: json["sso_url"],
        sloUrl:
            json["slo_url"] === undefined
                ? undefined
                : json["slo_url"] === null
                  ? null
                  : json["slo_url"],
        allowIdpInitiated:
            json["allow_idp_initiated"] == null ? undefined : json["allow_idp_initiated"],
        nameIdPolicy:
            json["name_id_policy"] == null
                ? undefined
                : SAMLNameIDPolicyEnumFromJSON(json["name_id_policy"]),
        bindingType:
            json["binding_type"] == null
                ? undefined
                : BindingTypeEnumFromJSON(json["binding_type"]),
        digestAlgorithm:
            json["digest_algorithm"] == null
                ? undefined
                : DigestAlgorithmEnumFromJSON(json["digest_algorithm"]),
        signatureAlgorithm:
            json["signature_algorithm"] == null
                ? undefined
                : SignatureAlgorithmEnumFromJSON(json["signature_algorithm"]),
        signedAssertion: json["signed_assertion"] == null ? undefined : json["signed_assertion"],
        signedResponse: json["signed_response"] == null ? undefined : json["signed_response"],
        verificationKp:
            json["verification_kp"] === undefined
                ? undefined
                : json["verification_kp"] === null
                  ? null
                  : json["verification_kp"],
        signingKp:
            json["signing_kp"] === undefined
                ? undefined
                : json["signing_kp"] === null
                  ? null
                  : json["signing_kp"],
        encryptionKp:
            json["encryption_kp"] === undefined
                ? undefined
                : json["encryption_kp"] === null
                  ? null
                  : json["encryption_kp"],
        verificationKpRing:
            json["verification_kp_ring"] === undefined
                ? undefined
                : json["verification_kp_ring"] === null
                  ? null
                  : json["verification_kp_ring"],
        signingKpRing:
            json["signing_kp_ring"] === undefined
                ? undefined
                : json["signing_kp_ring"] === null
                  ? null
                  : json["signing_kp_ring"],
        encryptionKpRing:
            json["encryption_kp_ring"] === undefined
                ? undefined
                : json["encryption_kp_ring"] === null
                  ? null
                  : json["encryption_kp_ring"],
        verificationKpOverride:
            json["verification_kp_override"] == null ? undefined : json["verification_kp_override"],
        signingKpOverride:
            json["signing_kp_override"] == null ? undefined : json["signing_kp_override"],
        encryptionKpOverride:
            json["encryption_kp_override"] == null ? undefined : json["encryption_kp_override"],
        freezeVerificationKp:
            json["freeze_verification_kp"] == null ? undefined : json["freeze_verification_kp"],
        freezeSigningKp: json["freeze_signing_kp"] == null ? undefined : json["freeze_signing_kp"],
        freezeEncryptionKp:
            json["freeze_encryption_kp"] == null ? undefined : json["freeze_encryption_kp"],
        localOverrideSet:
            json["local_override_set"] == null ? undefined : json["local_override_set"],
        metadataSnapshot: json["metadata_snapshot"],
        metadataLastImport:
            json["metadata_last_import"] == null
                ? null
                : parseDateTime(json["metadata_last_import"]),
        metadataHash: json["metadata_hash"],
        created: json["created"] == null ? json["created"] : parseDateTime(json["created"]),
        lastUpdated:
            json["last_updated"] == null
                ? json["last_updated"]
                : parseDateTime(json["last_updated"]),
    };
}

export function SAMLIDPToJSON(json: any): SAMLIDP {
    return SAMLIDPToJSONTyped(json, false);
}

export function SAMLIDPToJSONTyped(
    value?: Omit<
        SAMLIDP,
        | "pk"
        | "uuid"
        | "metadataSnapshot"
        | "metadataLastImport"
        | "metadataHash"
        | "created"
        | "lastUpdated"
    > | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        entity_id: value["entityId"],
        enabled: value["enabled"],
        sso_url: value["ssoUrl"],
        slo_url: value["sloUrl"],
        allow_idp_initiated: value["allowIdpInitiated"],
        name_id_policy: SAMLNameIDPolicyEnumToJSON(value["nameIdPolicy"]),
        binding_type: BindingTypeEnumToJSON(value["bindingType"]),
        digest_algorithm: DigestAlgorithmEnumToJSON(value["digestAlgorithm"]),
        signature_algorithm: SignatureAlgorithmEnumToJSON(value["signatureAlgorithm"]),
        signed_assertion: value["signedAssertion"],
        signed_response: value["signedResponse"],
        verification_kp: value["verificationKp"],
        signing_kp: value["signingKp"],
        encryption_kp: value["encryptionKp"],
        verification_kp_ring: value["verificationKpRing"],
        signing_kp_ring: value["signingKpRing"],
        encryption_kp_ring: value["encryptionKpRing"],
        verification_kp_override: value["verificationKpOverride"],
        signing_kp_override: value["signingKpOverride"],
        encryption_kp_override: value["encryptionKpOverride"],
        freeze_verification_kp: value["freezeVerificationKp"],
        freeze_signing_kp: value["freezeSigningKp"],
        freeze_encryption_kp: value["freezeEncryptionKp"],
        local_override_set: value["localOverrideSet"],
    };
}
