/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SAMLIDPCompare } from "./SAMLIDPCompare";
import { SAMLIDPCompareFromJSON, SAMLIDPCompareToJSON } from "./SAMLIDPCompare";

/**
 * Apply result payload for one IdP entity.
 * @export
 * @interface SAMLIDPApplyResult
 */
export interface SAMLIDPApplyResult {
    /**
     *
     */
    entityId: string;
    /**
     *
     */
    status: string;
    /**
     *
     */
    reason?: string | null;
    /**
     *
     */
    objectPk?: number | null;
    /**
     *
     */
    compare?: SAMLIDPCompare | null;
}

/**
 * Check if a given object implements the SAMLIDPApplyResult interface.
 */
export function instanceOfSAMLIDPApplyResult(value: object): value is SAMLIDPApplyResult {
    if (
        (!("entityId" in (value as Record<string, any>)) &&
            !("entity_id" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["entityId"] === undefined &&
            (value as Record<string, any>)["entity_id"] === undefined)
    )
        return false;
    if (!("status" in value) || value["status"] === undefined) return false;
    return true;
}

export function SAMLIDPApplyResultFromJSON(json: any): SAMLIDPApplyResult {
    return SAMLIDPApplyResultFromJSONTyped(json, false);
}

export function SAMLIDPApplyResultFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): SAMLIDPApplyResult {
    if (json == null) {
        return json;
    }
    return {
        entityId: json["entity_id"],
        status: json["status"],
        reason:
            json["reason"] === undefined
                ? undefined
                : json["reason"] === null
                  ? null
                  : json["reason"],
        objectPk:
            json["object_pk"] === undefined
                ? undefined
                : json["object_pk"] === null
                  ? null
                  : json["object_pk"],
        compare:
            json["compare"] === undefined
                ? undefined
                : json["compare"] === null
                  ? null
                  : SAMLIDPCompareFromJSON(json["compare"]),
    };
}

export function SAMLIDPApplyResultToJSON(json: any): SAMLIDPApplyResult {
    return SAMLIDPApplyResultToJSONTyped(json, false);
}

export function SAMLIDPApplyResultToJSONTyped(
    value?: SAMLIDPApplyResult | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        entity_id: value["entityId"],
        status: value["status"],
        reason: value["reason"],
        object_pk: value["objectPk"],
        compare: SAMLIDPCompareToJSON(value["compare"]),
    };
}
