/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Compare result for one IdP entity.
 * @export
 * @interface SAMLIDPCompare
 */
export interface SAMLIDPCompare {
    /**
     *
     */
    entityId: string;
    /**
     *
     */
    _exists: boolean;
    /**
     *
     */
    runtimeChanged: boolean;
    /**
     *
     */
    certChanged: boolean;
    /**
     *
     */
    runtimeDeviated: boolean;
    /**
     *
     */
    certDeviated: boolean;
    /**
     *
     */
    runtimeDiffFields?: Array<string>;
    /**
     *
     */
    certDiffFields?: Array<string>;
    /**
     *
     */
    runtimeLocked: boolean;
    /**
     *
     */
    certLocked: boolean;
    /**
     *
     */
    targetPk?: number | null;
}

/**
 * Check if a given object implements the SAMLIDPCompare interface.
 */
export function instanceOfSAMLIDPCompare(value: object): value is SAMLIDPCompare {
    if (
        (!("entityId" in (value as Record<string, any>)) &&
            !("entity_id" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["entityId"] === undefined &&
            (value as Record<string, any>)["entity_id"] === undefined)
    )
        return false;
    if (
        (!("_exists" in (value as Record<string, any>)) &&
            !("exists" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["_exists"] === undefined &&
            (value as Record<string, any>)["exists"] === undefined)
    )
        return false;
    if (
        (!("runtimeChanged" in (value as Record<string, any>)) &&
            !("runtime_changed" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["runtimeChanged"] === undefined &&
            (value as Record<string, any>)["runtime_changed"] === undefined)
    )
        return false;
    if (
        (!("certChanged" in (value as Record<string, any>)) &&
            !("cert_changed" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["certChanged"] === undefined &&
            (value as Record<string, any>)["cert_changed"] === undefined)
    )
        return false;
    if (
        (!("runtimeDeviated" in (value as Record<string, any>)) &&
            !("runtime_deviated" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["runtimeDeviated"] === undefined &&
            (value as Record<string, any>)["runtime_deviated"] === undefined)
    )
        return false;
    if (
        (!("certDeviated" in (value as Record<string, any>)) &&
            !("cert_deviated" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["certDeviated"] === undefined &&
            (value as Record<string, any>)["cert_deviated"] === undefined)
    )
        return false;
    if (
        (!("runtimeLocked" in (value as Record<string, any>)) &&
            !("runtime_locked" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["runtimeLocked"] === undefined &&
            (value as Record<string, any>)["runtime_locked"] === undefined)
    )
        return false;
    if (
        (!("certLocked" in (value as Record<string, any>)) &&
            !("cert_locked" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["certLocked"] === undefined &&
            (value as Record<string, any>)["cert_locked"] === undefined)
    )
        return false;
    return true;
}

export function SAMLIDPCompareFromJSON(json: any): SAMLIDPCompare {
    return SAMLIDPCompareFromJSONTyped(json, false);
}

export function SAMLIDPCompareFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): SAMLIDPCompare {
    if (json == null) {
        return json;
    }
    return {
        entityId: json["entity_id"],
        _exists: json["exists"],
        runtimeChanged: json["runtime_changed"],
        certChanged: json["cert_changed"],
        runtimeDeviated: json["runtime_deviated"],
        certDeviated: json["cert_deviated"],
        runtimeDiffFields:
            json["runtime_diff_fields"] == null ? undefined : json["runtime_diff_fields"],
        certDiffFields: json["cert_diff_fields"] == null ? undefined : json["cert_diff_fields"],
        runtimeLocked: json["runtime_locked"],
        certLocked: json["cert_locked"],
        targetPk:
            json["target_pk"] === undefined
                ? undefined
                : json["target_pk"] === null
                  ? null
                  : json["target_pk"],
    };
}

export function SAMLIDPCompareToJSON(json: any): SAMLIDPCompare {
    return SAMLIDPCompareToJSONTyped(json, false);
}

export function SAMLIDPCompareToJSONTyped(
    value?: SAMLIDPCompare | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        entity_id: value["entityId"],
        exists: value["_exists"],
        runtime_changed: value["runtimeChanged"],
        cert_changed: value["certChanged"],
        runtime_deviated: value["runtimeDeviated"],
        cert_deviated: value["certDeviated"],
        runtime_diff_fields: value["runtimeDiffFields"],
        cert_diff_fields: value["certDiffFields"],
        runtime_locked: value["runtimeLocked"],
        cert_locked: value["certLocked"],
        target_pk: value["targetPk"],
    };
}
