/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { NameIdPolicyF88Enum } from "./NameIdPolicyF88Enum";
import { NameIdPolicyF88EnumFromJSON, NameIdPolicyF88EnumToJSON } from "./NameIdPolicyF88Enum";
import type { SloBindingEnum } from "./SloBindingEnum";
import { SloBindingEnumFromJSON, SloBindingEnumToJSON } from "./SloBindingEnum";
import type { SsoBindingEnum } from "./SsoBindingEnum";
import { SsoBindingEnumFromJSON, SsoBindingEnumToJSON } from "./SsoBindingEnum";

/**
 * Serializer for IdP DTO payloads used by preview/apply.
 * @export
 * @interface SAMLIDPDTORequest
 */
export interface SAMLIDPDTORequest {
    /**
     *
     */
    entityId: string;
    /**
     *
     */
    displayName?: string | null;
    /**
     *
     */
    ssoBinding: SsoBindingEnum;
    /**
     *
     */
    ssoLocation: string;
    /**
     *
     */
    wantAuthnRequestsSigned?: boolean;
    /**
     *
     */
    nameIdPolicy?: NameIdPolicyF88Enum;
    /**
     *
     */
    signingCertPems?: Array<string>;
    /**
     *
     */
    encryptionCertPems?: Array<string>;
    /**
     *
     */
    sloBinding?: SloBindingEnum | null;
    /**
     *
     */
    sloLocation?: string | null;
}

/**
 * Check if a given object implements the SAMLIDPDTORequest interface.
 */
export function instanceOfSAMLIDPDTORequest(value: object): value is SAMLIDPDTORequest {
    if (
        (!("entityId" in (value as Record<string, any>)) &&
            !("entity_id" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["entityId"] === undefined &&
            (value as Record<string, any>)["entity_id"] === undefined)
    )
        return false;
    if (
        (!("ssoBinding" in (value as Record<string, any>)) &&
            !("sso_binding" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["ssoBinding"] === undefined &&
            (value as Record<string, any>)["sso_binding"] === undefined)
    )
        return false;
    if (
        (!("ssoLocation" in (value as Record<string, any>)) &&
            !("sso_location" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["ssoLocation"] === undefined &&
            (value as Record<string, any>)["sso_location"] === undefined)
    )
        return false;
    return true;
}

export function SAMLIDPDTORequestFromJSON(json: any): SAMLIDPDTORequest {
    return SAMLIDPDTORequestFromJSONTyped(json, false);
}

export function SAMLIDPDTORequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): SAMLIDPDTORequest {
    if (json == null) {
        return json;
    }
    return {
        entityId: json["entity_id"],
        displayName:
            json["display_name"] === undefined
                ? undefined
                : json["display_name"] === null
                  ? null
                  : json["display_name"],
        ssoBinding: SsoBindingEnumFromJSON(json["sso_binding"]),
        ssoLocation: json["sso_location"],
        wantAuthnRequestsSigned:
            json["want_authn_requests_signed"] == null
                ? undefined
                : json["want_authn_requests_signed"],
        nameIdPolicy:
            json["name_id_policy"] == null
                ? undefined
                : NameIdPolicyF88EnumFromJSON(json["name_id_policy"]),
        signingCertPems: json["signing_cert_pems"] == null ? undefined : json["signing_cert_pems"],
        encryptionCertPems:
            json["encryption_cert_pems"] == null ? undefined : json["encryption_cert_pems"],
        sloBinding:
            json["slo_binding"] === undefined
                ? undefined
                : json["slo_binding"] === null
                  ? null
                  : SloBindingEnumFromJSON(json["slo_binding"]),
        sloLocation:
            json["slo_location"] === undefined
                ? undefined
                : json["slo_location"] === null
                  ? null
                  : json["slo_location"],
    };
}

export function SAMLIDPDTORequestToJSON(json: any): SAMLIDPDTORequest {
    return SAMLIDPDTORequestToJSONTyped(json, false);
}

export function SAMLIDPDTORequestToJSONTyped(
    value?: SAMLIDPDTORequest | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        entity_id: value["entityId"],
        display_name: value["displayName"],
        sso_binding: SsoBindingEnumToJSON(value["ssoBinding"]),
        sso_location: value["ssoLocation"],
        want_authn_requests_signed: value["wantAuthnRequestsSigned"],
        name_id_policy: NameIdPolicyF88EnumToJSON(value["nameIdPolicy"]),
        signing_cert_pems: value["signingCertPems"],
        encryption_cert_pems: value["encryptionCertPems"],
        slo_binding: SloBindingEnumToJSON(value["sloBinding"]),
        slo_location: value["sloLocation"],
    };
}
