/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SAMLSPCompare } from "./SAMLSPCompare";
import { SAMLSPCompareFromJSON, SAMLSPCompareToJSON } from "./SAMLSPCompare";

/**
 * Apply result payload for one SP entity.
 * @export
 * @interface SAMLSPApplyResult
 */
export interface SAMLSPApplyResult {
    /**
     *
     */
    entityId: string;
    /**
     *
     */
    status: string;
    /**
     *
     */
    reason?: string | null;
    /**
     *
     */
    objectPk?: number | null;
    /**
     *
     */
    compare?: SAMLSPCompare | null;
}

/**
 * Check if a given object implements the SAMLSPApplyResult interface.
 */
export function instanceOfSAMLSPApplyResult(value: object): value is SAMLSPApplyResult {
    if (
        (!("entityId" in (value as Record<string, any>)) &&
            !("entity_id" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["entityId"] === undefined &&
            (value as Record<string, any>)["entity_id"] === undefined)
    )
        return false;
    if (!("status" in value) || value["status"] === undefined) return false;
    return true;
}

export function SAMLSPApplyResultFromJSON(json: any): SAMLSPApplyResult {
    return SAMLSPApplyResultFromJSONTyped(json, false);
}

export function SAMLSPApplyResultFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): SAMLSPApplyResult {
    if (json == null) {
        return json;
    }
    return {
        entityId: json["entity_id"],
        status: json["status"],
        reason:
            json["reason"] === undefined
                ? undefined
                : json["reason"] === null
                  ? null
                  : json["reason"],
        objectPk:
            json["object_pk"] === undefined
                ? undefined
                : json["object_pk"] === null
                  ? null
                  : json["object_pk"],
        compare:
            json["compare"] === undefined
                ? undefined
                : json["compare"] === null
                  ? null
                  : SAMLSPCompareFromJSON(json["compare"]),
    };
}

export function SAMLSPApplyResultToJSON(json: any): SAMLSPApplyResult {
    return SAMLSPApplyResultToJSONTyped(json, false);
}

export function SAMLSPApplyResultToJSONTyped(
    value?: SAMLSPApplyResult | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        entity_id: value["entityId"],
        status: value["status"],
        reason: value["reason"],
        object_pk: value["objectPk"],
        compare: SAMLSPCompareToJSON(value["compare"]),
    };
}
