/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { parseDateTime } from "../runtime";
import type { SAMLBindingsEnum } from "./SAMLBindingsEnum";
import { SAMLBindingsEnumFromJSON, SAMLBindingsEnumToJSON } from "./SAMLBindingsEnum";
import type { SAMLNameIDPolicyEnum } from "./SAMLNameIDPolicyEnum";
import { SAMLNameIDPolicyEnumFromJSON, SAMLNameIDPolicyEnumToJSON } from "./SAMLNameIDPolicyEnum";

/**
 * Serializer for nested SAML service provider entities.
 * @export
 * @interface SAMLSP
 */
export interface SAMLSP {
    /**
     *
     */
    readonly pk: number;
    /**
     *
     */
    readonly uuid: string;
    /**
     *
     */
    name?: string;
    /**
     * SAML EntityID (Issuer)
     */
    entityId: string;
    /**
     *
     */
    enabled?: boolean;
    /**
     *
     */
    acsUrl: string;
    /**
     *
     */
    spBinding?: SAMLBindingsEnum;
    /**
     *
     */
    slsUrl?: string;
    /**
     *
     */
    slsBinding?: SAMLBindingsEnum;
    /**
     *
     */
    authnRequestsSigned?: boolean;
    /**
     *
     */
    wantAssertionsSigned?: boolean;
    /**
     *
     */
    nameIdPolicy?: SAMLNameIDPolicyEnum;
    /**
     *
     */
    verificationKp?: string | null;
    /**
     *
     */
    signingKp?: string | null;
    /**
     *
     */
    encryptionKp?: string | null;
    /**
     *
     */
    verificationKpRing?: string | null;
    /**
     *
     */
    signingKpRing?: string | null;
    /**
     *
     */
    encryptionKpRing?: string | null;
    /**
     * Use local key; otherwise inherit from owner.
     */
    verificationKpOverride?: boolean;
    /**
     * Use local key; otherwise inherit from owner.
     */
    signingKpOverride?: boolean;
    /**
     * Use local key; otherwise inherit from owner.
     */
    encryptionKpOverride?: boolean;
    /**
     *
     */
    freezeVerificationKp?: boolean;
    /**
     *
     */
    freezeSigningKp?: boolean;
    /**
     *
     */
    freezeEncryptionKp?: boolean;
    /**
     *
     */
    localOverrideSet?: boolean;
    /**
     * If enabled, use this SAMLSP's property mappings instead of provider mappings.
     */
    propertyMappingsOverride?: boolean;
    /**
     * Per-SP property mappings.
     */
    propertyMappings?: Array<string>;
    /**
     *
     */
    readonly metadataSnapshot: { [key: string]: any };
    /**
     *
     */
    readonly metadataLastImport: Date | null;
    /**
     *
     */
    readonly metadataHash: string;
    /**
     *
     */
    readonly created: Date;
    /**
     *
     */
    readonly lastUpdated: Date;
}

/**
 * Check if a given object implements the SAMLSP interface.
 */
export function instanceOfSAMLSP(value: object): value is SAMLSP {
    if (!("pk" in value) || value["pk"] === undefined) return false;
    if (!("uuid" in value) || value["uuid"] === undefined) return false;
    if (
        (!("entityId" in (value as Record<string, any>)) &&
            !("entity_id" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["entityId"] === undefined &&
            (value as Record<string, any>)["entity_id"] === undefined)
    )
        return false;
    if (
        (!("acsUrl" in (value as Record<string, any>)) &&
            !("acs_url" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["acsUrl"] === undefined &&
            (value as Record<string, any>)["acs_url"] === undefined)
    )
        return false;
    if (
        (!("metadataSnapshot" in (value as Record<string, any>)) &&
            !("metadata_snapshot" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["metadataSnapshot"] === undefined &&
            (value as Record<string, any>)["metadata_snapshot"] === undefined)
    )
        return false;
    if (
        (!("metadataLastImport" in (value as Record<string, any>)) &&
            !("metadata_last_import" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["metadataLastImport"] === undefined &&
            (value as Record<string, any>)["metadata_last_import"] === undefined)
    )
        return false;
    if (
        (!("metadataHash" in (value as Record<string, any>)) &&
            !("metadata_hash" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["metadataHash"] === undefined &&
            (value as Record<string, any>)["metadata_hash"] === undefined)
    )
        return false;
    if (!("created" in value) || value["created"] === undefined) return false;
    if (
        (!("lastUpdated" in (value as Record<string, any>)) &&
            !("last_updated" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["lastUpdated"] === undefined &&
            (value as Record<string, any>)["last_updated"] === undefined)
    )
        return false;
    return true;
}

export function SAMLSPFromJSON(json: any): SAMLSP {
    return SAMLSPFromJSONTyped(json, false);
}

export function SAMLSPFromJSONTyped(json: any, ignoreDiscriminator: boolean): SAMLSP {
    if (json == null) {
        return json;
    }
    return {
        pk: json["pk"],
        uuid: json["uuid"],
        name: json["name"] == null ? undefined : json["name"],
        entityId: json["entity_id"],
        enabled: json["enabled"] == null ? undefined : json["enabled"],
        acsUrl: json["acs_url"],
        spBinding:
            json["sp_binding"] == null ? undefined : SAMLBindingsEnumFromJSON(json["sp_binding"]),
        slsUrl: json["sls_url"] == null ? undefined : json["sls_url"],
        slsBinding:
            json["sls_binding"] == null ? undefined : SAMLBindingsEnumFromJSON(json["sls_binding"]),
        authnRequestsSigned:
            json["authn_requests_signed"] == null ? undefined : json["authn_requests_signed"],
        wantAssertionsSigned:
            json["want_assertions_signed"] == null ? undefined : json["want_assertions_signed"],
        nameIdPolicy:
            json["name_id_policy"] == null
                ? undefined
                : SAMLNameIDPolicyEnumFromJSON(json["name_id_policy"]),
        verificationKp:
            json["verification_kp"] === undefined
                ? undefined
                : json["verification_kp"] === null
                  ? null
                  : json["verification_kp"],
        signingKp:
            json["signing_kp"] === undefined
                ? undefined
                : json["signing_kp"] === null
                  ? null
                  : json["signing_kp"],
        encryptionKp:
            json["encryption_kp"] === undefined
                ? undefined
                : json["encryption_kp"] === null
                  ? null
                  : json["encryption_kp"],
        verificationKpRing:
            json["verification_kp_ring"] === undefined
                ? undefined
                : json["verification_kp_ring"] === null
                  ? null
                  : json["verification_kp_ring"],
        signingKpRing:
            json["signing_kp_ring"] === undefined
                ? undefined
                : json["signing_kp_ring"] === null
                  ? null
                  : json["signing_kp_ring"],
        encryptionKpRing:
            json["encryption_kp_ring"] === undefined
                ? undefined
                : json["encryption_kp_ring"] === null
                  ? null
                  : json["encryption_kp_ring"],
        verificationKpOverride:
            json["verification_kp_override"] == null ? undefined : json["verification_kp_override"],
        signingKpOverride:
            json["signing_kp_override"] == null ? undefined : json["signing_kp_override"],
        encryptionKpOverride:
            json["encryption_kp_override"] == null ? undefined : json["encryption_kp_override"],
        freezeVerificationKp:
            json["freeze_verification_kp"] == null ? undefined : json["freeze_verification_kp"],
        freezeSigningKp: json["freeze_signing_kp"] == null ? undefined : json["freeze_signing_kp"],
        freezeEncryptionKp:
            json["freeze_encryption_kp"] == null ? undefined : json["freeze_encryption_kp"],
        localOverrideSet:
            json["local_override_set"] == null ? undefined : json["local_override_set"],
        propertyMappingsOverride:
            json["property_mappings_override"] == null
                ? undefined
                : json["property_mappings_override"],
        propertyMappings: json["property_mappings"] == null ? undefined : json["property_mappings"],
        metadataSnapshot: json["metadata_snapshot"],
        metadataLastImport:
            json["metadata_last_import"] == null
                ? null
                : parseDateTime(json["metadata_last_import"]),
        metadataHash: json["metadata_hash"],
        created: json["created"] == null ? json["created"] : parseDateTime(json["created"]),
        lastUpdated:
            json["last_updated"] == null
                ? json["last_updated"]
                : parseDateTime(json["last_updated"]),
    };
}

export function SAMLSPToJSON(json: any): SAMLSP {
    return SAMLSPToJSONTyped(json, false);
}

export function SAMLSPToJSONTyped(
    value?: Omit<
        SAMLSP,
        | "pk"
        | "uuid"
        | "metadataSnapshot"
        | "metadataLastImport"
        | "metadataHash"
        | "created"
        | "lastUpdated"
    > | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        entity_id: value["entityId"],
        enabled: value["enabled"],
        acs_url: value["acsUrl"],
        sp_binding: SAMLBindingsEnumToJSON(value["spBinding"]),
        sls_url: value["slsUrl"],
        sls_binding: SAMLBindingsEnumToJSON(value["slsBinding"]),
        authn_requests_signed: value["authnRequestsSigned"],
        want_assertions_signed: value["wantAssertionsSigned"],
        name_id_policy: SAMLNameIDPolicyEnumToJSON(value["nameIdPolicy"]),
        verification_kp: value["verificationKp"],
        signing_kp: value["signingKp"],
        encryption_kp: value["encryptionKp"],
        verification_kp_ring: value["verificationKpRing"],
        signing_kp_ring: value["signingKpRing"],
        encryption_kp_ring: value["encryptionKpRing"],
        verification_kp_override: value["verificationKpOverride"],
        signing_kp_override: value["signingKpOverride"],
        encryption_kp_override: value["encryptionKpOverride"],
        freeze_verification_kp: value["freezeVerificationKp"],
        freeze_signing_kp: value["freezeSigningKp"],
        freeze_encryption_kp: value["freezeEncryptionKp"],
        local_override_set: value["localOverrideSet"],
        property_mappings_override: value["propertyMappingsOverride"],
        property_mappings: value["propertyMappings"],
    };
}
