# Generated by Django 5.2.10 on 2026-02-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_crypto", "0006_create_certificate_reference"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="certificatereference",
            new_name="authentik_c_certifi_7d9d4e_idx",
            old_name="crypto_certref_cert_idx",
        ),
        migrations.RenameIndex(
            model_name="certificatereference",
            new_name="authentik_c_ref_mod_a1852e_idx",
            old_name="crypto_certref_ref_idx",
        ),
        migrations.RenameIndex(
            model_name="certificatereference",
            new_name="authentik_c_usage_11b624_idx",
            old_name="crypto_certref_usage_idx",
        ),
        migrations.AlterField(
            model_name="certificatereference",
            name="fingerprint_sha256",
            field=models.CharField(
                editable=False,
                help_text="SHA-256 fingerprint of the referenced certificate (hex).",
                max_length=95,
            ),
        ),
        migrations.AlterField(
            model_name="certificatereference",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="certificatereference",
            name="ref_model",
            field=models.CharField(
                help_text='Model label of the referencing object, e.g. "authentik_providers_saml.SAMLProvider".',
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="certificatereference",
            name="ref_pk",
            field=models.CharField(
                help_text="Primary key of the referencing object serialized as string.",
                max_length=64,
            ),
        ),
        migrations.AddIndex(
            model_name="certificatereference",
            index=models.Index(
                fields=["fingerprint_sha256"], name="authentik_c_fingerp_a477ec_idx"
            ),
        ),
    ]
