# Generated by Django 5.2.10 on 2026-02-25 03:37

import authentik.lib.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentik_crypto",
            "0007_rename_crypto_certref_cert_idx_authentik_c_certifi_7d9d4e_idx_and_more",
        ),
        ("authentik_providers_saml", "0021_samlprovider_spliting_sp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="samlsp",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="samlsp",
            name="uniq_samlsp_provider_entity_id",
        ),
        migrations.RemoveIndex(
            model_name="samlsp",
            name="samlsp_entity_id_idx",
        ),
        migrations.RenameIndex(
            model_name="samlsp",
            new_name="authentik_p_provide_5ba82e_idx",
            old_name="samlsp_provider_enabled_idx",
        ),
        migrations.AddField(
            model_name="samlsession",
            name="samlsp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="authentik_providers_saml.samlsp",
            ),
        ),
        migrations.AddField(
            model_name="samlsp",
            name="encryption_kp_mode",
            field=models.CharField(
                choices=[
                    ("inherit", "Inherit provider setting"),
                    ("set", "Use local key"),
                    ("none", "Disable key (no key)"),
                ],
                default="inherit",
                help_text="How encryption_kp is resolved: inherit provider, use local key, or explicitly disable encryption key.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="samlsp",
            name="freeze_encryption_kp",
            field=models.BooleanField(
                default=False,
                help_text="Do not overwrite encryption_kp during metadata apply/import. Useful for certificate rollover handling or local pinning.",
            ),
        ),
        migrations.AddField(
            model_name="samlsp",
            name="freeze_signing_kp",
            field=models.BooleanField(
                default=False,
                help_text="Do not overwrite signing_kp during metadata apply/import. Useful for certificate rollover handling or local pinning.",
            ),
        ),
        migrations.AddField(
            model_name="samlsp",
            name="freeze_verification_kp",
            field=models.BooleanField(
                default=False,
                help_text="Do not overwrite verification_kp during metadata apply/import. Useful for certificate rollover handling or local pinning.",
            ),
        ),
        migrations.AddField(
            model_name="samlsp",
            name="has_local_override",
            field=models.BooleanField(
                default=False,
                help_text="UI/diagnostic flag indicating local changes may exist relative to metadata-derived defaults. Protocol processing does not read this flag.",
            ),
        ),
        migrations.AddField(
            model_name="samlsp",
            name="property_mappings",
            field=models.ManyToManyField(
                blank=True,
                help_text="Per-SP property mappings. If empty, provider property mappings are used.",
                related_name="samlsp_overrides",
                to="authentik_providers_saml.samlpropertymapping",
            ),
        ),
        migrations.AddField(
            model_name="samlsp",
            name="property_mappings_override",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, use this SAMLSP's property mappings instead of provider mappings. An empty set is treated as an explicit override (no attributes).",
            ),
        ),
        migrations.AddField(
            model_name="samlsp",
            name="signing_kp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="authentik_crypto.certificatekeypair",
            ),
        ),
        migrations.AddField(
            model_name="samlsp",
            name="signing_kp_mode",
            field=models.CharField(
                choices=[
                    ("inherit", "Inherit provider setting"),
                    ("set", "Use local key"),
                    ("none", "Disable key (no key)"),
                ],
                default="inherit",
                help_text="How signing_kp is resolved: inherit provider, use local key, or explicitly disable signing key.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="samlsp",
            name="verification_kp_mode",
            field=models.CharField(
                choices=[
                    ("inherit", "Inherit provider setting"),
                    ("set", "Use local key"),
                    ("none", "Disable key (no key)"),
                ],
                default="inherit",
                help_text="How verification_kp is resolved: inherit provider, use local key, or explicitly disable verification key.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="samlprovider",
            name="strict_acs_url",
            field=models.BooleanField(
                default=True,
                help_text="When disabled, the ACS URL from the SAML request is usedinstead of the provider's configured ACS URL.",
            ),
        ),
        migrations.AlterField(
            model_name="samlsp",
            name="acs_url",
            field=models.TextField(
                validators=[authentik.lib.models.DomainlessURLValidator(schemes=("http", "https"))]
            ),
        ),
        migrations.AlterField(
            model_name="samlsp",
            name="enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="samlsp",
            name="encryption_kp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="authentik_crypto.certificatekeypair",
            ),
        ),
        migrations.AlterField(
            model_name="samlsp",
            name="entity_id",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="samlsp",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="samlsp",
            name="name",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="samlsp",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_providers",
                to="authentik_providers_saml.samlprovider",
            ),
        ),
        migrations.AlterField(
            model_name="samlsp",
            name="sls_binding",
            field=models.TextField(
                choices=[("redirect", "Redirect"), ("post", "Post")], default="post"
            ),
        ),
        migrations.AlterField(
            model_name="samlsp",
            name="sls_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="samlsp",
            name="sp_binding",
            field=models.TextField(
                choices=[("redirect", "Redirect"), ("post", "Post")], default="post"
            ),
        ),
        migrations.AlterField(
            model_name="samlsp",
            name="verification_kp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="authentik_crypto.certificatekeypair",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="samlsp",
            unique_together={("provider", "entity_id")},
        ),
        migrations.AddIndex(
            model_name="samlsp",
            index=models.Index(
                fields=["provider", "entity_id"], name="authentik_p_provide_566486_idx"
            ),
        ),
    ]
