# Generated by Django 5.2.10 on 2026-02-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_providers_saml", "0022_alter_samlsp_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="samlsp",
            name="encryption_kp_mode",
        ),
        migrations.RemoveField(
            model_name="samlsp",
            name="signing_kp_mode",
        ),
        migrations.RemoveField(
            model_name="samlsp",
            name="verification_kp_mode",
        ),
        migrations.AddField(
            model_name="samlsp",
            name="encryption_kp_override",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, use this SP's local encryption_kp (may be null to disable). If disabled, inherit provider setting.",
            ),
        ),
        migrations.AddField(
            model_name="samlsp",
            name="signing_kp_override",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, use this SP's local signing_kp (may be null to disable). If disabled, inherit provider setting.",
            ),
        ),
        migrations.AddField(
            model_name="samlsp",
            name="verification_kp_override",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, use this SP's local verification_kp (may be null to disable). If disabled, inherit provider setting.",
            ),
        ),
    ]
