# Generated by Django 5.2.11 on 2026-04-06 14:41

import uuid

import django.db.models.deletion
from django.db import migrations, models

import authentik.admin.files.fields
import authentik.lib.models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_crypto", "0007_certificatekeypairring_certificatekeypairringbinding_and_more"),
        ("authentik_providers_saml", "0022_samlprovider_encryption_kp_ring_and_more"),
        ("authentik_sources_saml", "0023_samlsource_encryption_kp_ring_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SAMLMetadataFeed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                (
                    "metadata_name",
                    authentik.admin.files.fields.FileField(
                        help_text="Path in admin/files (usage=saml_metadata)."
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "signing_certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="authentik_crypto.certificatekeypair",
                    ),
                ),
            ],
            options={
                "verbose_name": "SAML Metadata Feed",
                "verbose_name_plural": "SAML Metadata Feeds",
            },
        ),
        migrations.CreateModel(
            name="SAMLIDP",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.TextField(blank=True, default="")),
                ("entity_id", models.TextField(help_text="SAML EntityID (Issuer)")),
                ("enabled", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "verification_kp_override",
                    models.BooleanField(
                        default=False, help_text="Use local key; otherwise inherit from owner."
                    ),
                ),
                (
                    "signing_kp_override",
                    models.BooleanField(
                        default=False, help_text="Use local key; otherwise inherit from owner."
                    ),
                ),
                (
                    "encryption_kp_override",
                    models.BooleanField(
                        default=False, help_text="Use local key; otherwise inherit from owner."
                    ),
                ),
                ("freeze_verification_kp", models.BooleanField(default=False)),
                ("freeze_signing_kp", models.BooleanField(default=False)),
                ("freeze_encryption_kp", models.BooleanField(default=False)),
                ("local_override_set", models.BooleanField(default=False)),
                ("metadata_snapshot", models.JSONField(blank=True, default=dict)),
                ("metadata_last_import", models.DateTimeField(blank=True, default=None, null=True)),
                ("metadata_hash", models.CharField(blank=True, default="", max_length=64)),
                (
                    "sso_url",
                    models.TextField(
                        help_text="URL that the initial Login request is sent to.",
                        validators=[
                            authentik.lib.models.DomainlessURLValidator(schemes=("http", "https"))
                        ],
                        verbose_name="SSO URL",
                    ),
                ),
                (
                    "slo_url",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="Optional URL if your IDP supports Single-Logout.",
                        null=True,
                        validators=[
                            authentik.lib.models.DomainlessURLValidator(schemes=("http", "https"))
                        ],
                        verbose_name="SLO URL",
                    ),
                ),
                ("allow_idp_initiated", models.BooleanField(default=False)),
                (
                    "name_id_policy",
                    models.TextField(
                        choices=[
                            ("urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress", "Email"),
                            ("urn:oasis:names:tc:SAML:2.0:nameid-format:persistent", "Persistent"),
                            ("urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName", "X509"),
                            (
                                "urn:oasis:names:tc:SAML:2.0:nameid-format:WindowsDomainQualifiedName",
                                "Windows",
                            ),
                            ("urn:oasis:names:tc:SAML:2.0:nameid-format:transient", "Transient"),
                            (
                                "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified",
                                "Unspecified",
                            ),
                        ],
                        default="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent",
                    ),
                ),
                (
                    "binding_type",
                    models.CharField(
                        choices=[
                            ("REDIRECT", "Redirect Binding"),
                            ("POST", "POST Binding"),
                            ("POST_AUTO", "POST Binding with auto-confirmation"),
                        ],
                        default="REDIRECT",
                        max_length=100,
                    ),
                ),
                (
                    "digest_algorithm",
                    models.TextField(
                        choices=[
                            ("http://www.w3.org/2000/09/xmldsig#sha1", "SHA1"),
                            ("http://www.w3.org/2001/04/xmlenc#sha256", "SHA256"),
                            ("http://www.w3.org/2001/04/xmldsig-more#sha384", "SHA384"),
                            ("http://www.w3.org/2001/04/xmlenc#sha512", "SHA512"),
                        ],
                        default="http://www.w3.org/2001/04/xmlenc#sha256",
                    ),
                ),
                (
                    "signature_algorithm",
                    models.TextField(
                        choices=[
                            ("http://www.w3.org/2000/09/xmldsig#rsa-sha1", "RSA-SHA1"),
                            ("http://www.w3.org/2001/04/xmldsig-more#rsa-sha256", "RSA-SHA256"),
                            ("http://www.w3.org/2001/04/xmldsig-more#rsa-sha384", "RSA-SHA384"),
                            ("http://www.w3.org/2001/04/xmldsig-more#rsa-sha512", "RSA-SHA512"),
                            ("http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha1", "ECDSA-SHA1"),
                            ("http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256", "ECDSA-SHA256"),
                            ("http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384", "ECDSA-SHA384"),
                            ("http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512", "ECDSA-SHA512"),
                            ("http://www.w3.org/2000/09/xmldsig#dsa-sha1", "DSA-SHA1"),
                        ],
                        default="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
                    ),
                ),
                ("signed_assertion", models.BooleanField(default=True)),
                ("signed_response", models.BooleanField(default=False)),
                (
                    "encryption_kp",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="authentik_crypto.certificatekeypair",
                        verbose_name="Encryption Keypair",
                    ),
                ),
                (
                    "encryption_kp_ring",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="authentik_crypto.certificatekeypairring",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_providers",
                        to="authentik_sources_saml.samlsource",
                    ),
                ),
                (
                    "signing_kp",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="authentik_crypto.certificatekeypair",
                        verbose_name="Signing Keypair",
                    ),
                ),
                (
                    "signing_kp_ring",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="authentik_crypto.certificatekeypairring",
                    ),
                ),
                (
                    "verification_kp",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="authentik_crypto.certificatekeypair",
                        verbose_name="Verification Certificate",
                    ),
                ),
                (
                    "verification_kp_ring",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="authentik_crypto.certificatekeypairring",
                    ),
                ),
            ],
            options={
                "verbose_name": "SAML Identity Provider",
                "verbose_name_plural": "SAML Identity Providers",
                "indexes": [
                    models.Index(
                        fields=["parent", "entity_id"], name="authentik_p_parent__e05913_idx"
                    ),
                    models.Index(
                        fields=["parent", "enabled"], name="authentik_p_parent__0cd6db_idx"
                    ),
                ],
                "unique_together": {("parent", "entity_id")},
            },
        ),
        migrations.CreateModel(
            name="SAMLMetadataBind",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.TextField(
                        choices=[("sp", "Service Provider"), ("idp", "Identity Provider")]
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata_binds",
                        to="authentik_providers_saml.samlprovider",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata_binds",
                        to="authentik_sources_saml.samlsource",
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="binds",
                        to="authentik_providers_saml.samlmetadatafeed",
                    ),
                ),
            ],
            options={
                "verbose_name": "SAML Metadata Bind",
                "verbose_name_plural": "SAML Metadata Binds",
                "indexes": [
                    models.Index(fields=["feed", "kind"], name="authentik_p_feed_id_3902bb_idx"),
                    models.Index(fields=["provider"], name="authentik_p_provide_9fec4a_idx"),
                    models.Index(fields=["source"], name="authentik_p_source__85277f_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("kind", "sp"),
                                ("provider__isnull", False),
                                ("source__isnull", True),
                            ),
                            models.Q(
                                ("kind", "idp"),
                                ("source__isnull", False),
                                ("provider__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="ak_saml_metadata_bind_owner_matches_kind",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("provider__isnull", False)),
                        fields=("feed", "provider"),
                        name="ak_saml_metadata_bind_feed_provider_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("source__isnull", False)),
                        fields=("feed", "source"),
                        name="ak_saml_metadata_bind_feed_source_unique",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SAMLSP",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.TextField(blank=True, default="")),
                ("entity_id", models.TextField(help_text="SAML EntityID (Issuer)")),
                ("enabled", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "verification_kp_override",
                    models.BooleanField(
                        default=False, help_text="Use local key; otherwise inherit from owner."
                    ),
                ),
                (
                    "signing_kp_override",
                    models.BooleanField(
                        default=False, help_text="Use local key; otherwise inherit from owner."
                    ),
                ),
                (
                    "encryption_kp_override",
                    models.BooleanField(
                        default=False, help_text="Use local key; otherwise inherit from owner."
                    ),
                ),
                ("freeze_verification_kp", models.BooleanField(default=False)),
                ("freeze_signing_kp", models.BooleanField(default=False)),
                ("freeze_encryption_kp", models.BooleanField(default=False)),
                ("local_override_set", models.BooleanField(default=False)),
                ("metadata_snapshot", models.JSONField(blank=True, default=dict)),
                ("metadata_last_import", models.DateTimeField(blank=True, default=None, null=True)),
                ("metadata_hash", models.CharField(blank=True, default="", max_length=64)),
                (
                    "acs_url",
                    models.TextField(
                        validators=[
                            authentik.lib.models.DomainlessURLValidator(schemes=("http", "https"))
                        ]
                    ),
                ),
                (
                    "sp_binding",
                    models.TextField(
                        choices=[("redirect", "Redirect"), ("post", "Post")], default="post"
                    ),
                ),
                ("sls_url", models.TextField(blank=True, default="")),
                (
                    "sls_binding",
                    models.TextField(
                        choices=[("redirect", "Redirect"), ("post", "Post")], default="post"
                    ),
                ),
                ("authn_requests_signed", models.BooleanField(default=False)),
                ("want_assertions_signed", models.BooleanField(default=False)),
                (
                    "name_id_policy",
                    models.TextField(
                        choices=[
                            ("urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress", "Email"),
                            ("urn:oasis:names:tc:SAML:2.0:nameid-format:persistent", "Persistent"),
                            ("urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName", "X509"),
                            (
                                "urn:oasis:names:tc:SAML:2.0:nameid-format:WindowsDomainQualifiedName",
                                "Windows",
                            ),
                            ("urn:oasis:names:tc:SAML:2.0:nameid-format:transient", "Transient"),
                            (
                                "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified",
                                "Unspecified",
                            ),
                        ],
                        default="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified",
                    ),
                ),
                (
                    "property_mappings_override",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "If enabled, use this SAMLSP's property mappings instead of provider"
                            " mappings."
                        ),
                    ),
                ),
                (
                    "encryption_kp",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="authentik_crypto.certificatekeypair",
                        verbose_name="Encryption Keypair",
                    ),
                ),
                (
                    "encryption_kp_ring",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="authentik_crypto.certificatekeypairring",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_providers",
                        to="authentik_providers_saml.samlprovider",
                    ),
                ),
                (
                    "property_mappings",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Per-SP property mappings.",
                        related_name="samlsp_overrides",
                        to="authentik_providers_saml.samlpropertymapping",
                    ),
                ),
                (
                    "signing_kp",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="authentik_crypto.certificatekeypair",
                        verbose_name="Signing Keypair",
                    ),
                ),
                (
                    "signing_kp_ring",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="authentik_crypto.certificatekeypairring",
                    ),
                ),
                (
                    "verification_kp",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="authentik_crypto.certificatekeypair",
                        verbose_name="Verification Certificate",
                    ),
                ),
                (
                    "verification_kp_ring",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="authentik_crypto.certificatekeypairring",
                    ),
                ),
            ],
            options={
                "verbose_name": "SAML Service Provider",
                "verbose_name_plural": "SAML Service Providers",
                "indexes": [
                    models.Index(
                        fields=["parent", "entity_id"], name="authentik_p_parent__e2eaa0_idx"
                    ),
                    models.Index(
                        fields=["parent", "enabled"], name="authentik_p_parent__2c78d2_idx"
                    ),
                ],
                "unique_together": {("parent", "entity_id")},
            },
        ),
    ]
