# Generated by Django 5.2.14 on 2026-05-16 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_providers_saml", "0022_remove_samlprovider_issuer_and_more"),
        ("authentik_providers_saml", "0023_samlmetadatafeed_samlidp_samlmetadatabind_samlsp"),
    ]

    operations = []
