# Generated by Django 5.2.15 on 2026-07-19 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_providers_saml", "0023_merge_20260719_0143"),
        ("authentik_providers_saml", "0024_merge_20260516_0505"),
    ]

    operations = []
